### PR TITLE
Make the new Avada "Off Canvas" type transalatable

### PR DESCRIPTION
**Pull request by dgwatkins**

### CODE REVIEW

**Comment by dgwatkins** [comment]
@OnTheGoSystems/compatibility please review

**Comment by strategio** [comment]
@dgwatkins, did you also test when WPML is set to "Translate Everything"?

**Comment by dgwatkins** [comment]
@strategio actually, I only tested translate-everything.

**Comment by dgwatkins** [comment]
It works, but I found a problem when conditions include a post id.

I will merge here and follow up in the YT ticket.

**Comment by dgwatkins** [comment]
@strategio if you approve, this part is correct and we can merge.

Further work will be done separately

**Review by strategio — APPROVED** [review]
Thanks @dgwatkins +1

**Pull request merged**
