### PR TITLE
[Elementor Pro] Translate "price" field from Price list widget

### PR DESCRIPTION
**Pull request by andrescifuentesr**
- Making the Price field translatable for Price list widget
- https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-6636

### CODE REVIEW

**Review by strategio — APPROVED** [review]
+1 @andrescifuentesr

**Comment by strategio** [comment]
Merged and deployed @andrescifuentesr.

**Comment by strategio** [comment]
@andrescifuentesr, I completely missed the failing CI pipeline that was failing on this PR.
I was always convinced that a failing pipeline would block the merge, but it's not...

There was an real issue with a missing `>` in your change, and I had to fix it right away => 
https://github.com/OnTheGoSystems/wpml-config/pull/407/files#diff-bc9c4a7432e8e85ec3b80ccdf4e8c6bbac13991f17ab0d0376e87e1da650fe2eL350

**Comment by andrescifuentesr** [comment]
Thank you for your quick intervention @strategio. As I didn't initially modify that line, I checked it but I didn't spot the issue at that moment. I'll check better next time, specially if a pipeline fails.

**Pull request merged**
