### PR TITLE
wpmltm-3322 Cornerstone classic custom headlines registered for translation twice

### PR DESCRIPTION
**Pull request by kagg-design**
`ignore-content="1"` added to Classic Custom Headline and Classic Features Headline.

Removed repetitive names from `<shortcode-list>`

Some formatting has done.

https://onthegosystems.myjetbrains.com/youtrack/issue/wpmltm-3322

### CODE REVIEW

**Comment by kagg-design** [comment]
@OnTheGoSystems/wpml Please review

**Comment by kagg-design** [comment]
@strategio yes, that is the reason. So, I have blocked registering of strings in 2 shortcodes.

**Comment by strategio** [comment]
Got it @kagg-design! I think it's worth a comment in the config file otherwise it will be hard to remember why we did this in 6 months.

Could you add:

```
<!-- This block is already registered through the API, we don't want to register it twice -->
```

**Comment by kagg-design** [comment]
@strategio sure, done!

**Pull request merged**
