### PR TITLE
Corrected icon aria-label attribute for icon block

### PR DESCRIPTION
**Pull request by bfintal**

### CODE REVIEW

**Comment by strategio** [comment]
Hi @bfintal, did you have a chance to look into this again?

**Comment by bfintal** [comment]
Hey @strategio, apologies for just getting back now, and thanks for the heads up. Yes, it really should have been `@aria-label` from the start, but we incorrectly added in `@alt` :) So it should be okay to replace it completely.

**Comment by strategio** [comment]
Thanks for the confirmation @bfintal!

I've merged your fix in our `master` branch and synchronized it to our CDN (it should propagate now).

**Comment by bfintal** [comment]
Thanks @strategio !

**Pull request merged**
