### PR TITLE
Set labels for ATE Gen3

### PR DESCRIPTION
**Pull request by dgwatkins**
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-419

### CODE REVIEW

**Comment by dgwatkins** [comment]
I believe we can merge this already because we are just updating the labels.

@OnTheGoSystems/compatibility

**Comment by dgwatkins** [comment]
Note that we don't need specific labels for every element because we try to put together the label automatically. We only set a specific label when the automatic label doesn't match the requirements.

**Review by strategio — COMMENTED** [review]
@dgwatkins, I quickly scanned the changes and it looks good. The only question is about the order of the items in the config: Our current config does not respect a clear order (alphabetical or other), and in your changes you also changed the order of some items, but still it's not alphabetical. Did you opted for another specific order?

**Comment by dgwatkins** [comment]
No @strategio

As far as I can see, the order of the XML elements has nothing to do with it.
ATE receives string in the order they are registered in (string_location field).

I did change the order of divi shortcode definitions to confirm this.

I left it changed because it makes more sense to have the titles at the top and the rest below.

**Review by strategio — APPROVED** [review]
+1 @dgwatkins

**Pull request merged**
