### PR TITLE
Updating Elementor XML - compsupp-7621

### PR DESCRIPTION
**Pull request by Kitilyes**
See https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7621/Create-XML-config-for-Elementor-Floating-Elements

### CODE REVIEW

**Review by dgwatkins — COMMENTED** [review]
Isn't `contact-buttons-var-2` missing?

**Review by dgwatkins — COMMENTED** [review]
Was `contact_tooltip` removed intentionally @Kitilyes?

It seems to still be valid.

**Review by dgwatkins — COMMENTED** [review]
The formatting is incorrect around line 522 @Kitilyes

**Comment by Kitilyes** [comment]
- There is no `contact-buttons-var-2` in Elementor source code
- There are 12 different versions of this widget, `contact-buttons-var-XX` , contact_tooltip was part of a [previously added widget ](https://github.com/OnTheGoSystems/wpml-config/commit/cc833d5056fdcb3cdda086dc45fd9a408b272af6) `contact-buttons-var-4` belongs to the same prooject, so it made sense to move this widget under  `contact-buttons-var-3` for better reading.
- You are right, 527 and 528 have wrong indenting , do I do another commit?

**Comment by dgwatkins** [comment]
Yes please @Kitilyes

**Comment by Kitilyes** [comment]
Done @dgwatkins

**Review by dgwatkins — APPROVED** [review]
Looks good to me @Kitilyes 

Is it ready to merge and deploy?

**Comment by Kitilyes** [comment]
Yes, it is ready.

**Comment by dgwatkins** [comment]
merged and deployed, thanks @Kitilyes

**Pull request merged**
