### PR TITLE
Add "Click to Chat" plugin config

### PR DESCRIPTION
**Pull request by vukvukovich**

### CODE REVIEW

**Comment by amElnagdy** [comment]
@dgwatkins this needs to be synced?

**Comment by dgwatkins** [comment]
Lets discuss this on Wednesdays meeting

**Comment by amElnagdy** [comment]
@dgwatkins I'm not sure what to discuss. What I meant is does anything need to be synced after the merge?

**Comment by dgwatkins** [comment]
@amElnagdy It does need to be sync'd but I am not sure if we should add every little plugin just for a pipeline to pass earlier. We need to set some requirements for adding items here or it will soon get out of hand (ie: popularity threshold?).

**Comment by amElnagdy** [comment]
@dgwatkins I understand. We are already doing this. This is the [plugin page](https://wordpress.org/plugins/click-to-chat-for-whatsapp/) on WordPress.org

**Pull request merged**
