### PR TITLE
Beta support for Muffin page builder (betheme)

### PR DESCRIPTION
**Pull request by dgwatkins**

### CODE REVIEW

**Comment by amElnagdy** [comment]
@dgwatkins if we're going to host the config file, should not we merge the config from the local file and set the online one to override the local one? Or ask the author to include this in the local file. 

Bottom line, clients should have a complete config file. What do you think?

**Comment by dgwatkins** [comment]
@amElnagdy I set it to override_local

If the author decides to maintain it we can remove it from here.
Sounds good?

**Comment by dgwatkins** [comment]
@amElnagdy oh, I gotcha now.
The theme already has a wpml-config.xml file.
Merging it next .... thanks

**Comment by dgwatkins** [comment]
@amElnagdy Can you take a second look?
Thanks!

**Pull request merged**
