### PR TITLE
Updating Elementor XML - compsupp-7594

### PR DESCRIPTION
**Pull request by diiegopereira**
See https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7594

### CODE REVIEW

**Review by strategio — COMMENTED** [review]
@diiegopereira, it looks good. Did you also find other variations of the name "contact-buttons-var-4" (maybe "contact-buttons-var-1"), perhaps we should also support it?

**Comment by diiegopereira** [comment]
@strategio I checked Elementor code and found that they have at least 10 variations of this widget.

I believe we will have to test and generate the XML configuration for each of them, as they have different structures. For this, I created a new ticket (compsupp-7621).

Perhaps we can merge this PR, and then add the other configs in a new PR?

**Review by strategio — APPROVED** [review]
Thanks @diiegopereira +1

**Comment by strategio** [comment]
That's merged @diiegopereira.

@dgwatkins, I could not connect to the server to deploy, could you please do it if you can?

**Comment by dgwatkins** [comment]
Deployed @strategio

**Pull request merged**
