### PR TITLE
wpml-config file for Forminator plugin

### PR DESCRIPTION
**Pull request by kkarpieszuk**
@comp-code-review please review and add

### CODE REVIEW

**Comment by kkarpieszuk** [comment]
@dgwatkins @srdjan-jcc or anyone, please review and merge

**Comment by dgwatkins** [comment]
Hi @kkarpieszuk 
You need to add the corresponding entry to config-index.xml
Thanks!

**Comment by kkarpieszuk** [comment]
@dgwatkins file updated, please check. I set override flag to false because we are going to switch this preference anyway if author will be cooperating. This is just a temporary file

**Comment by dgwatkins** [comment]
I have never tried setting `override_local` to false.
If we don't want an override, we usually just omit the whole attribute.
However, I dont think its important in this case because its temporary.

**Pull request merged**
