### PR TITLE
Add restricted day fields set to copy in bookings

### PR DESCRIPTION
**Pull request by ofwald**
Adds `_wc_booking_has_restricted_days` and `_wc_booking_has_restricted_days` set to copy.
Fix indentation in previous fields.

### CODE REVIEW

**Comment by ofwald** [comment]
@strategio I should have done two commits probably :|

and I can't ping @comp-code-review in `reviewers`, am I missing something?

**Comment by dgwatkins** [comment]
Its ok @ofwald 

I can still see the real changes adding `?w=1` to the URL:
https://github.com/OnTheGoSystems/wpml-config/pull/232/files?w=1

**Review by dgwatkins — APPROVED** [review]
@ofwald looks good to me

**Comment by ofwald** [comment]
Thanks!

**Pull request merged**
