### PR TITLE
Added support for Yoast 22.0 - Organization schema

### PR DESCRIPTION
**Pull request by andrescifuentesr**
Allowing to translate new custom fields added by Yoast 22.0.
- Organization description.
- Alternate organization name
https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3932

### CODE REVIEW

**Comment by strategio** [comment]
@andrescifuentesr, can you please also add the new keys to the PRO version too. That way we'll keep things in sync until we'll remove the duplicate in the other ticket you created.

**Comment by andrescifuentesr** [comment]
I hope that it should be fine now, @strategio.

**Review by strategio — APPROVED** [review]
Sounds good @andrescifuentesr, thanks!

**Comment by strategio** [comment]
Merged and deployed.

**Pull request merged**
