### PR TITLE
Adding support for excluding and including posts

### PR DESCRIPTION
**Pull request by andrescifuentesr**
- Adding support for excluding and including posts.
- Removing email_list list.

Reference:
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-6339/Testing-Bloom-Elegant-Themes

### CODE REVIEW

**Comment by strategio** [comment]
@andrescifuentesr, could you please include a link to the YT ticket in your commit message?

**Comment by andrescifuentesr** [comment]
Sorry about it @strategio, ticket added.

**Review by strategio — APPROVED** [review]
Can I merge and deploy that @andrescifuentesr?

**Comment by andrescifuentesr** [comment]
Yes, it is OK to merge and deploy it @strategio.

**Comment by strategio** [comment]
Merged and deployed @andrescifuentesr!

**Pull request merged**
