### PR TITLE
[for 4.1.0] Add media config for shortcodes in Fusion Builder (Avada)

### PR DESCRIPTION
**Pull request by strategio**
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-5855

### CODE REVIEW

**Comment by dgwatkins** [comment]
@strategio 
If this is meant to be merged for 4.1.0 please indicate it in the title.
You can see how in other open pulls.

**Comment by strategio** [comment]
Yes @dgwatkins, it's for 4.1.0.

I don't know if you have a specific process for this, but I created a `develop` branch which is the target branch for this PR.

When WPML 4.1.0 is released, we can just merge the `develop` branch into `master` (after rebasing).

What do you think?

**Comment by dgwatkins** [comment]
ok, thats the proper way :-)
Thanks

**Comment by strategio** [comment]
@dgwatkins, can I let you merge all the approved PRs?

**Comment by dgwatkins** [comment]
Ok, ill take care if you prefer

**Pull request merged**
