### PR TITLE
Configuration file for SiteOrigin page builder integration

### PR DESCRIPTION
**Pull request by dgwatkins**
Started off with the standard WordPress widgets and a few premium ones to cover the different use cases.

The parent merge request is: https://git.onthegosystems.com/glue-plugins/wpml/wpml-page-builders/-/merge_requests/3

https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3498

### CODE REVIEW

**Comment by dgwatkins** [comment]
It is expected for this to fail, until the new XSD file is published with core

**Review by strategio — DISMISSED** [review]
What a long config @dgwatkins :) +1

**Comment by strategio** [comment]
BTW @dgwatkins, is there already a local config file in SiteOrigin?

**Comment by dgwatkins** [comment]
@strategio no, there isn't.

This file should probably go in their plugin instead.

**Comment by dgwatkins** [comment]
@strategio I had to add the built-with-page-builder element to avoid problems when there are no strings in a page.

Can you re-review please?

**Review by strategio — APPROVED** [review]

**Review by kkarpieszuk — APPROVED** [review]

**Review by kkarpieszuk — DISMISSED** [review]

**Review by andreas-pa — APPROVED** [review]

**Pull request merged**
