### PR TITLE
compsupp-5684: Icon box and Recommendation widgets

### PR DESCRIPTION
**Pull request by andrescifuentesr**
[Uncode]: Adding two new shortcodes for translating:
- Icon Box title
- Recommended Posts

### CODE REVIEW

**Review by dgwatkins — CHANGES_REQUESTED** [review]
@andrescifuentesr 
It looks good but I think we should add the vc_icon->title to the main js_composer file too.

**Comment by andrescifuentesr** [comment]
I missed this notification @dgwatkins, sorry. Done!

**Comment by strategio** [comment]
Thanks @andrescifuentesr!

I add to re-create a branch with yours because there is a `.DS_Store` file included (we don't want this).

I invited you as a contributor for this repository. So in the future you should be able to push your branches to this repo, and it we be simpler for all of us if we need to adjust something on your branch.

Let me know if you can't properly access to the repo.

**Comment by strategio** [comment]
Closing here, it was merged in https://github.com/OnTheGoSystems/wpml-config/pull/214.

**Pull request closed without merging**
