### PR TITLE
[DONT MERGE] Add support for Avada Forms shortcodes

### PR DESCRIPTION
**Pull request by amElnagdy**
https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3556

### CODE REVIEW

**Comment by amElnagdy** [comment]
@OnTheGoSystems/compatibility please don't merge until we get a reply from Avada team.

**Review by strategio — APPROVED** [review]

**Comment by strategio** [comment]
@amElnagdy, I added a commit with some fixes related to [wpmlcore-8268](https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-8268). I'll let you check!

**Review by amElnagdy — COMMENTED** [review]
Nicely done @strategio :)

**Comment by amElnagdy** [comment]
> @amElnagdy Apparently we have conflicts here.
> 
> Can we merge once they are solved? All clear with the author?

We're doing the work on our side (@strategio did). The author tried but it didn't work. 

Regarding the conflicts, I didn't get it. Should I do something here?

**Comment by dgwatkins** [comment]
@amElnagdy Thanks for the info

@strategio Can we merge this?
if so, can you resolve the conflicts please?

**Comment by strategio** [comment]
> @strategio Can we merge this?
> if so, can you resolve the conflicts please?

@dgwatkins, I believe we should wait for next WPML version (patch or 4.5.0) to deploy this new config because this is supposed to work with changes in https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-8268.

I will rebase the branch and address the conflicts.

**Comment by strategio** [comment]
It was a conflict with https://github.com/OnTheGoSystems/wpml-config/commit/4b10cdde92b191912909600a0f6745b8bd241586#diff-4973ef650f6b0b523d91355ecb9bec706170b3be6043603feb4dd18344e5ed6e, fixed now. @amElnagdy, can you please check the changes again?

**Comment by amElnagdy** [comment]
It looks OK to me @strategio 👍

**Review by dgwatkins — APPROVED** [review]

**Comment by amElnagdy** [comment]
@strategio as wpmlcore-8268 is done, should we merge here?

**Comment by strategio** [comment]
> @strategio as wpmlcore-8268 is done, should we merge here?

@amElnagdy, wpmlcore-8268 is included in WPML 4.4.11 but this version has not been released yet. So let's wait for the release as the tag suggests.

**Comment by strategio** [comment]
CDN updated!

**Pull request merged**
