### PR TITLE
Config for WooCommerce Gift Cards

### PR DESCRIPTION
**Pull request by GeorgeBotsev**
Config for the e-mail strings for WooCommerce Gift Cards plugin https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-6072

### CODE REVIEW

**Comment by dgwatkins** [comment]
Hi @GeorgeBotsev 

Can you add a line to `config-index.xml`?
You can follow the same format as other entries.
The `id` is the folder name and inside we need the Plugin Name as it appears in the plugin header.

**Comment by strategio** [comment]
Hi @GeorgeBotsev (sorry to hijack the conversation), could please also add a link to the YT ticket in the commit message?

**Comment by GeorgeBotsev** [comment]
> > Hi @GeorgeBotsev
> > Can you add a line to `config-index.xml`? You can follow the same format as other entries. The `id` is the folder name and inside we need the Plugin Name as it appears in the plugin header.
> 
> I will add it.

This is now handled.
I also added the YouTrack tricket to the commit message as requested.

**Comment by dgwatkins** [comment]
Looks great @GeorgeBotsev 

Thanks

**Review by dgwatkins — APPROVED** [review]
Merged and sync'd to S3

**Pull request merged**
