### PR TITLE
[wpmldev-2884] Sync core changes to remote XML

### PR DESCRIPTION
**Pull request by dgwatkins**
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmldev-2884/

### CODE REVIEW

**Comment by dgwatkins** [comment]
@OnTheGoSystems/compatibility please review

**Review by strategio — APPROVED** [review]
Looks good @dgwatkins!

But please ping Ivan in the ticket to make sure he is aware of that (need to sync with the remote config) and he will share with the rest of his team.

**Comment by dgwatkins** [comment]
> But please ping Ivan in the ticket to make sure he is aware of that (need to sync with the remote config) and he will share with the rest of his team.

I asked him via MM to share with his team, I will add a note to the ticket too.

**Comment by dgwatkins** [comment]
Merged and deployed

**Pull request merged**
