### PR TITLE
Luster theme does not show properties for translated agent.

### PR DESCRIPTION
**Pull request by kagg-design**
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlcore-6765

### CODE REVIEW

**Comment by kagg-design** [comment]
@OnTheGoSystems/wpml Please review

**Comment by dgwatkins** [comment]
I am not sure we should add this here.

**Comment by kagg-design** [comment]
@dgwatkins why?

**Comment by dgwatkins** [comment]
1) We are in contact with the author, so we should ask him to include it in the theme instead.

2) Even if we had no author cooperation, we are missing the entry in config-index.xml

**Comment by kagg-design** [comment]
@dgwatkins I have added the item to config-index, thank you.

**Comment by dgwatkins** [comment]
Hi @vukvukovich 
You created the ticket wpmlcore-6765
Can I ask if you need wpml-config.xml here? 
It looks like you wanted to include it in XML configuration instead.
Let me know
Thanks
David

**Comment by dgwatkins** [comment]
I had a chat with Vuk over Mattermost.
He will review this file and complete it or remove it later on during the compatibility process.
So for now, let's merge it

**Pull request merged**
