### PR TITLE
[Merge for WPML 4.6] Add support for Divi widgets referencing product ids

### PR DESCRIPTION
**Pull request by strategio**
https://onthegosystems.myjetbrains.com/youtrack/issue/wpmlpb-275

### CODE REVIEW

**Comment by strategio** [comment]
@jamalbou, can you please give it a review?

**Comment by jamalbou** [comment]
+1 @strategio

**Review by jamalbou — APPROVED** [review]
+1 @strategio

**Comment by strategio** [comment]
Merged and deployed!

**Pull request merged**
