### PR TITLE
Comp 3618

### PR DESCRIPTION
**Pull request by izzi-hassan**
Adding Support for Oxygen Builder in the first commit. Please let me know if there's anything else that needs to happen to override local repository.

Second one is just sorting the Config Index, feel free to cherry pick the commit if there are any issue with that @dgwatkins

### CODE REVIEW

**Comment by izzi-hassan** [comment]
@dgwatkins @amElnagdy please review!

**Comment by izzi-hassan** [comment]
I have added some more XML config for the missing translatable widgets.

We are still missing support for the image, video and code block elements. I'll discuss this in MM.

**Comment by strategio** [comment]
Just one doubt @izzi-hassan: What is exactly the `ct_options` encoding? Is it handled by Oxygen Builder somewhere? Do you manage to set this encoding in WPML > Settings > Custom XML Config?

**Comment by izzi-hassan** [comment]
@strategio I'm improving this with a more oxygen-specific encoding name. I'm also discussing this in MM with David.

The code for handling this encoding is slightly different to how we handle regular urlencoded json:
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-5606#focus=Comments-102-461759.0-0

**Review by dgwatkins — COMMENTED** [review]
@izzi-hassan It looks good :+1:

Can you just double check that users without the `oxygen_ct_options` encoding won't have issues? Thanks!

**Comment by strategio** [comment]
Thanks @izzi-hassan! Indeed it's clearer to have a prefixed encoding name if it's a custom one.

And do you manage to set this encoding in WPML > Settings > Custom XML Config? I am asking because I am not sure of the rules we have in our `xsd` file. But after thinking twice, I believe it will work because now we are also validating our PR with the `xsd`.

LGTM +1

**Review by strategio — APPROVED** [review]

**Comment by izzi-hassan** [comment]
Yes, there are no issues with that custom encoding name being added to the WPML -> Settings -> Custom XML Configuration box.

Without the filters to handle this new encoding, we are facing the bug reported by our users, where we corrupt the translated json by running `htmlspecialchars` on it in `WPML\LIB\WP\Gutenberg\WPML_PB_Update_Shortcodes_In_Content::filter_attribute_translation `.

This is reported here:
https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-5606

Adding this encoding to the config does not change the behavior or throw any errors or exceptions even without the filters @dgwatkins

Please merge, and then I'll give everything one last test before publishing an erratum!

**Review by dgwatkins — APPROVED** [review]
according to XSD:
- attribute encoding can be any string
- custom field encoding is restricted to `[0-9a-z,]*`

so :+1: @izzi-hassan

**Pull request merged**
