### PR TITLE
[compsupp-7679] Uncode theme - Add translation to column links

### PR DESCRIPTION
**Pull request by nicolasviallet**
Uncode has an option to add a link to vc_column and make it clickable. 

Youtrack: https://onthegosystems.myjetbrains.com/youtrack/issue/compsupp-7679

### CODE REVIEW

**Comment by strategio** [comment]
@nicolasviallet, for WPBakery page builder, we also find it in [js_composer](https://github.com/OnTheGoSystems/wpml-config/blob/master/js_composer/wpml-config.xml#L392) and [js_composer-dt-the7](https://github.com/OnTheGoSystems/wpml-config/blob/master/js_composer-dt-the7/wpml-config.xml#L392C13-L392C33).

Could please also apply the same changes in these other configs? (unless you think it's very specific to Uncode)

Note: it's an old discrepancy between these 3 files that we have to deal with now.

**Comment by nicolasviallet** [comment]
@strategio we tested it for Visual Composer and it doesn't provide that feature.  It's specific to Uncode theme.

**Review by strategio — APPROVED** [review]
Sure @nicolasviallet, then it's fine +1

I'll merge it.

**Comment by strategio** [comment]
Deployed.

**Pull request merged**
