### PR TITLE
Popup Maker: prepare wpml-config.xml file

### PR DESCRIPTION
**Pull request by kkarpieszuk**
https://onthegosystems.myjetbrains.com/youtrack/issue/comp-3633

### CODE REVIEW

**Review by dgwatkins — APPROVED** [review]
:+1: @kkarpieszuk 

I'll sync right after merging

**Comment by kkarpieszuk** [comment]
thanks, comp please provide abother review

**Comment by dgwatkins** [comment]
@kkarpieszuk its already merged. 

We only require one review here :-)

**Comment by kkarpieszuk** [comment]
ah ok

**Pull request merged**
